services:
  - type: web
    name: af360bank
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true
    domains:
      - name: af360bank.onrender.com
      - name: comissoes.af360bank.onrender.com
    healthCheckPath: /
    autoDeploy: true
